spring:
  datasource:
    url: jdbc:mysql://localhost:3306/trustful_platform?useSSL=false&serverTimezone=UTC
    username: root
    password: Lcx0618.
    driver-class-name: com.mysql.cj.jdbc.Driver
  mybatis-plus:
    mapper-locations: classpath:mapper/**/*.xml
    type-aliases-package: com.lee.auth.entity
    configuration:
      map-underscore-to-camel-case: true
test:
  flag: from-db-module
jwt:
  secret: LiChengXinAiZhaoXinLing
  expiration: 3600  # 过期时间，单位：秒
